language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "nhenneaux"
    token:
      secure: "BKyLzhkKsbPnrnpfQhTz+4k+Lb667WJVdmruAtSp0JzvHweCRt5XUZgA3FjAzZMXMzgM29qRygl6wFRhDb9yVHGvZ+j0lVyh9EKp6IN5/L1Pf88y71R3SVi5gNaT4BIS4SlyTMDBE89YJ1hHFffGWwRadqvbkh/jm06XSCaQ8uvZgd96Lrf56v+sNXgyjtQHfA6X2ioG1+6YINhSGQCs1cQrWu6gguGyPo+esumpoI2zhT6tRb1hTdDJNqUtrkkEL1gdGomfkqvkMwdZdR5eGWO9K74EaVKJN5xUp75yOG+DPiWtsm+Yf0VzoPWca72i2PFXMgGPoyQ1/uQQZ/uADnEQMNjtpETv5SEWWLRtgS6W1XpEXDfoSc6D/VMbfetCNEoZSiDCF9zYjbHWDj5C+CtFBBrwS8at7B0wOYhCmr2ACBysywV6dT1iXrxxOJy5TZoNZvFA2DJYfa+PQWX5vdadhhqho/Ecf0qgSJLoRzLn9guZK+lexOk6KB+kgK7yK/D0iCaen+mcxdAJdagNBeD0d7mfx7SuRb0Fn85CuQCGk89Y7XC3Wk4BxTprFpDWVloxC+qK0IYwfvigZBPli+zbPhq6vuGRE9+TeUB0FxamJ1OlkgCxhWX+tPuqIkD21dX3mf9G8aStsRhonXDHSuE1SOpXp72A+auykoi99nQ="

script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=nhenneaux_jersey-http2-jetty-connector
