language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "nhenneaux"
    token:
      secure: "Thw34m6KAsLx2pcwBMZMcBm9vJfl6RvG00Enm4RK7+oo9MyodbAu69LuJ76Nwebhywxylxu+9bKNDaqlzKVo/DbVtdqOfRb9pY+oYm9yps/xNnULCpWNJLj6mfbiOzwe9rRUhZsyQhrL09Pnv0a3q81VKW+8N93Lhtw6a5tIS3njEmdxcYtuL7wzF6nKawwLx7dg14CTMFlXFMp2jYnK+7/kmYLHI7q67Xnb8kgtOmvQ63jkmnFg1hSlj/ETJcn/eFNAkplDXHrlGyUR+iFA5Ec2hRzSjEMTRwkUBG/jlK+SSd+c59a5RT1NaUHLAVB0GCbXk8sSfyBfSuJXoTxNxfP83yRVWHooyMQX9cnJ4d5n2SZVAsgJ0xkb7UZlHaGepvVy2ViXIx7qCdduIHmyoEhcngedQ4REgLHPWWK1jX381SlCHcUpdw6kfZqT6CeDBYT4wmk2HFKhCVu+hJrQ2BnZeiF9q1CCCc3J8/v+3gtwiOta0IvWTlQ9cag37uaVxGZNOs7AA/DlsHoSRuEHSwynNTkr1RoAzOcQA9pMQjtayHqRYibSqosJDIPwxPXPIVlkuKjS5M33oipb2Y2LzpuqGB2ha+dfUP//ib9Scqc1cn6yb4hw7yLu2e4Rhl7YvZ9V9qW4l05Lj2Fsdj8+Y4o3GxRjtfWtPidZkYo1epo="
script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=nhenneaux_jersey-http2-jetty-connector
